android/src/main/java/com/reactlibrary/JudoReactNativeModule.java, ios/RNJudo.m, sample-app/.gitignore, sample-app/android/app/build.gradle, sample-app/android/app/release/output.json, sample-app/android/app/src/main/res/values/strings.xml, sample-app/screens/DataConfig.tsx, sample-app/screens/Home.tsx, sample-app/screens/Settings.tsx, sample-app/yarn.lock
https://thedojo.atlassian.net/browse/EP-802
title="A cute kitten" width="182" height="378" />
=> [EP-802] HomeScreen refactor + UI changes

JudoPay.tsx, index.tsx, ios/RNJudo.m, sample-app/helpers/ApplePayDefaults.tsx, sample-app/helpers/JudoDefaults.tsx, sample-app/screens/Home/Home.tsx, sample-app/screens/Home/HomeData.tsx, sample-app/screens/Home/HomeProps.tsx, types/JudoApplePayTypes.tsx, types/JudoTypes.tsx
- Added the iOS Payment Method Screen to the React Native SDK
=> [SDK Update] Added Payment Method screen

JudoPay.tsx, ios/RNJudo.m, sample-app/screens/Home/Home.tsx, sample-app/screens/Home/HomeData.tsx, sample-app/screens/Home/HomeProps.tsx
- Added both Apple Pay payment and pre-auth support;
=> [SDK Updates] Added Apple Pay

android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt
- added type checking and error handling for android
=> [EP-853] - Android error handling

ios/Classes/RNJudo.h, ios/Classes/RNJudo.m, sample-app/ios/Podfile.lock, sample-app/screens/Home/HomeData.tsx, sample-app/screens/Settings/Settings.tsx, sample-app/screens/Settings/SettingsData.tsx, sample-app/screens/Settings/SettingsProps.tsx
- Added fix for Apple Pay losing JudoKit reference;
- Added settings for Apple Pay on the Settings page;
- Fixed typo for the `isSandboxed` toggle in the Settings page;
=> Added Apple Pay settings and fixes

sample-app/android/app/build.gradle, sample-app/android/build.gradle, sample-app/android/gradle/wrapper/gradle-wrapper.properties, sample-app/screens/Settings/SettingsData.tsx
- loading pay.cards library from maven
=> - Fixed settings crash in android

sample-app/App.tsx, sample-app/helpers/JudoDefaults.tsx, sample-app/screens/Home/Home.tsx
- Replaced the Back button from the Receipt screen with a Home button that navigates back to the main screen;
- The passed configuration to the Token Payments and PBBA screens now use the `reference()` method to generate unique references;
=> Added unique reference to PBBA and Token payments

android/build.gradle, android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt
Added isBankingAppAvailable method
Added order/bank/sale callback
=> Added missing PbBa functionality

android/src/main/java/com/reactlibrary/Extensions.kt, android/src/main/java/com/reactlibrary/Helpers.kt, android/src/main/java/com/reactlibrary/JudoReactNativeActivityEventListener.kt, android/src/test/java/com/reactlibrary/HelpersKtTest.kt, android/src/test/java/com/reactlibrary/JudoReactNativeActivityEventListenerTest.kt, android/src/test/java/com/reactlibrary/JudoReactNativeModuleTest.kt, android/src/test/java/com/reactlibrary/JudoReactNativePackageTest.kt, android/src/test/java/com/reactlibrary/JudoReadableMapExtensionsTest.kt, android/src/test/java/com/reactlibrary/UIConfigurationReadableMapExtensionsTest.kt
-Fix unit tests
-Added missing extension functions
-Refactored getAuthorization method
-Other adjustments
=> ANDROID - EP-1632 - Update wrapper unit tests

RNJudopay.podspec, ios/Podfile, package.json, sample-app/ios/Podfile, sample-app/ios/Podfile.lock
Note: Don't merge until iOS 2.1.3 is released
=> Updated version to 3.1.0

android/build.gradle, android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt, sample-app/.gitignore, sample-app/android/app/build.gradle
-Add 3DS for token payments no ui
-Added card scanning library to sample app gradle file
=> EP-1724 - Update android native SDK to latest version

android/src/main/java/com/reactlibrary/JudoReactNativeModule.kt
Call either token payment or pre-auth token payment according to payment widget type
=> EP-1727 - Token PreAuth routing as Payment bug

android/src/main/java/com/reactlibrary/Extensions.kt, android/src/test/java/com/reactlibrary/JudoReadableMapExtensionsTest.kt
=> Set isInitialRecurringPayment to false in android wrapper

package.json, sample-app/android/app/build.gradle, sample-app/package.json
Amended package.json files to trigger a fresh yarn install on CI pipe…line
=> Amended package.json files

RNJudopay.podspec, android/build.gradle, package.json, sample-app/android/app/build.gradle, sample-app/android/build.gradle, sample-app/ios/Podfile, sample-app/ios/Podfile.lock, sample-app/ios/sample-app.xcodeproj/project.pbxproj, sample-app/package.json
Bumps up package version
Updates native dependencies versions
=> Version bump up

RNJudopay.podspec, android/build.gradle, android/src/main/java/com/reactlibrary/Extensions.kt, android/src/main/java/com/reactlibrary/Helpers.kt, ios/Classes/Wrappers/RNWrappers.m, ios/Podfile, package.json, sample-app/android/app/build.gradle, sample-app/android/gradle/wrapper/gradle-wrapper.properties, sample-app/ios/Podfile, sample-app/ios/Podfile.lock, sample-app/ios/sample-app.xcodeproj/project.pbxproj, sample-app/package.json, sample-app/screens/Home/HomeData.tsx, sample-app/screens/Settings/SettingsData.tsx, types/JudoTypes.tsx
- AMEX support
- package version bump
=> Native dependencies updates

ios/Classes/RNJudo.m
=> Fixed the iOS Build issue in "3.4.1"

RNJudopay.podspec, android/build.gradle, android/src/main/java/com/reactlibrary/Helpers.kt, ios/Podfile, ios/Podfile.lock, ios/RNJudo.xcodeproj/project.pbxproj, package.json, sample-app/android/app/build.gradle, sample-app/ios/Podfile, sample-app/ios/Podfile.lock, sample-app/ios/sample-app.xcodeproj/project.pbxproj, sample-app/package.json, sample-app/screens/Settings/SettingsData.tsx
- Package version bump
- Native dependencies version update
=> Release 3.4.3

RNJudopay.podspec, android/build.gradle, ios/Podfile, package.json, sample-app/android/app/build.gradle, sample-app/ios/Podfile, sample-app/ios/Podfile.lock, sample-app/ios/sample-app.xcodeproj/project.pbxproj
- JudoKit-Android to `3.0.10`
- JudoKit-iOS to `3.1.3`
=> Native dependencies version bump

ios/Classes/Wrappers/RNWrappers.m, ios/Podfile.lock, ios/RNJudo.xcodeproj/project.pbxproj, sample-app/ios/sample-app.xcodeproj/project.pbxproj, types/JudoTypes.tsx
- Reverts `response.result` to old mappings
- Reverts `threeDSTwoMaxTimeout` type
=> Mappings reverts

__tests__/JudoGooglePayTypesTest.tsx, android/build.gradle, android/src/main/java/com/reactlibrary/Extensions.kt, android/src/main/java/com/reactlibrary/Helpers.kt, android/src/test/java/com/reactlibrary/AmountReadableMapExtensionsTest.kt, android/src/test/java/com/reactlibrary/GooglePayReadableMapExtensionsTest.kt, android/src/test/java/com/reactlibrary/HelpersKtTest.kt, android/src/test/java/com/reactlibrary/JudoReadableMapExtensionsTest.kt, android/src/test/java/com/reactlibrary/PrimaryAccountDetailsReadableMapExtensionsTest.kt, android/src/test/java/com/reactlibrary/ReferenceReadableMapExtensionsTest.kt, android/src/test/java/com/reactlibrary/UIConfigurationReadableMapExtensionsTest.kt, types/JudoGooglePayTypes.tsx
Left a TODO in `Helpers.kt` to add the below once the latest JudoKit-Android is released
```
//            .setAllowPrepaidCards(options.allowPrepaidCards)
//            .setAllowCreditCards(options.allowCreditCards)
```
=> CT-2674 Add missing Google Pay params

android/build.gradle, package.json, sample-app/android/app/build.gradle, sample-app/android/build.gradle, sample-app/ios/sample-app.xcodeproj/project.pbxproj, sample-app/package.json
To be updated when native android dependency will be available in prod.
=> CT-2780 - Removes custom PbBA repository name

.circleci/config.yml, example/.detoxrc.js, example/e2e/helpers.ts, example/package.json
* Changed to use Arm architecture as the Intel ones are being deprecated soon
* Using official RN orb for some things
* Using official Android image which already has most dependencies 
* Using what looks like default AVD even though I specified a Pixel, so something I need to figure out how to change, maybe look into using [Genymotion](https://www.genymotion.com/)?
* For these tests to run, it'll require a release of JudoKit-Android to pick up the new selectors
=> CT-2889 | UI Tests CI Setup

.circleci/config.yml, example/e2e/constants.ts, example/e2e/functional.test.ts, example/e2e/helpers.ts
* Add tests for step up transactions - more info [here](https://thedojo.atlassian.net/wiki/spaces/FE/pages/3619160090/Testing+step-up+flow)
* Refactor CI/CD script for better Slack notifications
* Fix a few small things here and there
=> CT-2952 | Step up flow UI tests

.circleci/config.yml, example/e2e/constants.ts, example/e2e/functional.test.ts, example/e2e/helpers.ts, example/src/Data/SettingsSections/threeDSTwoSection.ts
* Add tests to cover billing details section including input validation tests
* Refactor/organise selectors and add more helper functions
* Changes to the native SDK are required for these new tests
=> CT-2903 | Billing Details UI Tests

.circleci/config.yml, example/e2e/billinginfo.test.ts, example/e2e/constants.ts, example/e2e/helpers.ts, example/e2e/ideal.test.ts
=> CT-3014 | Basic set of iDEAL tests

.circleci/config.yml, example/e2e/billinginfo.test.ts, example/e2e/ideal.test.ts
* Comment out iDEAL tests which are not required just now
* Set country to UK on UK test as this defaults to US
=> Address test failures

.github/workflows/snyk.yml
* Sets up a Github workflow to scan this project and its dependencies for vulnerabilities.
=> DO-2166 - Set up Snyk scans
